name: macOS Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          # Skip Python 2.7, 3.5, and PyPy
          CIBW_SKIP: cp27-* cp35-* pp*
          CIBW_ARCHS_MACOS: "x86_64 arm64 universal2"
          CIBW_TEST_COMMAND: python -m low_index.test

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
